name: Snow Tunnel Monitor Full Auto
on:
  schedule:
    # 平日早尖峰 (台灣 07:30 - 08:30)
    - cron: '30-59 23 * * 0-4'
    - cron: '0-30 0 * * 1-5'
    # 平日晚尖峰 (台灣 17:00 - 18:00)
    - cron: '0-59 9 * * 1-5'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python main.py
      - name: Update page
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add index.html
          git commit -m "早晚尖峰自動更新" || exit 0
          git push
